# 通过OOB_IP来定位和区别交换机路由器设备
oob_IP_addr: "192.168.99.33/24"


# CSW有三层SVI
hostname: HubSW1
vlans:
  - vlan_id: 2020
    name: to_GW1
  - vlan_id: 2030
    name: to_GW2
  - vlan_id: 500
    name: intranet


svis:
  - name: Vlan2020
    ipv4:
      - address: 10.211.9.2/30

  - name: Vlan2030
    ipv4:
      - address: 10.212.9.2/16

  - name: Vlan500
    ipv4:
      - address: 10.200.200.1/24


l2_ports:
  - name: Ethernet0/0                  # GW_HUB1
    mode: access
    access_vlan: 2020
  - name: Ethernet0/1                  # GW_HUB2
    mode: access
    access_vlan: 2030

l3_ports:
  - name: Loopback1
    ipv4:
      - address: 10.8.8.8/32
  - name: Loopback2
    ipv4:
      - address: 10.8.8.9/32

# ios_static_routes 结构按地址族嵌套
static_routes:
  - address_families:
      - afi: ipv4
        routes:
          - dest: 0.0.0.0/0
            next_hops:
              - forward_router_address: 10.211.9.1
              - forward_router_address: 10.212.9.1

# 接口描述
interfaces_cfg:
  - name: Ethernet0/0
    description: "uplink-to-GW1"
    enabled: true                     # true = no shutdown;false = shutdown
  - name: Ethernet0/1
    description: "uplink-to-GW2"
    enabled: true

