# 通过OOB_IP来定位和区别交换机路由器设备
oob_IP_addr: "192.168.99.30/24"

# HubSW纯二层透传
hostname: HubSW1
vlans:
  - vlan_id: 3010
    name: ISP1
  - vlan_id: 3020
    name: ISP2


l2_ports:
  - name: Ethernet0/0                  # 注意 IOL 是 Ethernet0/x
    mode: access
    access_vlan: 3010
  - name: Ethernet0/3                  # 注意 IOL 是 Ethernet0/x
    mode: access
    access_vlan: 3010

  - name: Ethernet0/1                  # 注意 IOL 是 Ethernet0/x
    mode: access
    access_vlan: 3020
  - name: Ethernet0/2                  # 注意 IOL 是 Ethernet0/x
    mode: access
    access_vlan: 3020
