# 通过OOB_IP来定位和区别交换机路由器设备
oob_IP_addr: "192.168.99.252/24"


hostname: ISP1

l3_ports:
  - name: Ethernet0/0
    ipv4:
      - address:       # 面向 hub 的"公网"口

interfaces_cfg:
  - name: Ethernet0/0
    description: "to-Hub-ISP1"
    enabled: true

# ios_static_routes 结构按地址族嵌套
static_routes:
  - address_families:
      - afi: ipv4
        routes:
          - dest: 0.0.0.0/0
            next_hops:
              - forward_router_address: 59.3.3.1