# 通过OOB_IP来定位和区别交换机路由器设备
oob_IP_addr: "192.168.99.252/24"


hostname: ISP2

l3_ports:
  - name: Ethernet0/2
    ipv4:
      - address: 212.3.3.1/30        # 面向 hub 的"公网"口

  - name: Ethernet0/0
    ipv4:
      - address: 104.8.8.1/30         # GW012

  - name: Ethernet0/1
    ipv4:
      - address: 114.8.8.5/30        # GW034

  - name: Loopback10
    ipv4:
      - address: 119.29.29.29/32        # 公网





interfaces_cfg:
  - name: Ethernet0/2
    description: "to-Hub-ISP2"
    enabled: true
  - name: Ethernet0/0
    description: "to-GW012"
    enabled: true
  - name: Ethernet0/1
    description: "to-GW032"
    enabled: true
  - name: Loopback10
    description: "Internet_test"
    enabled: true



